---
- name: "Slurp builtin password file"
  slurp:
    path: "{{ playbook_dir }}/files/builtin_passwords.json"
  register: builtin_pass
  when: elastic_password | length == 0
  delegate_to: localhost

- name: "Get the password of elastic if the user exists"
  when: elastic_password | length == 0
  delegate_to: localhost
  block:

  - name: "Get the password of elastic"
    set_fact:
      elastic_password: "{{ builtin_pass.content | b64decode | from_json | json_query(query) }}"
    vars:
      query: "[?user=='elastic'].password | [0]"

  rescue:
  - name: "End the playbook since elastic password is not present in the file"
    meta: end_play
