---
# cat << EOF > /etc/sysconfig/logstash
# LOGSTASH_KEYSTORE_PASS=xxxx
# EOF
# chmod 600 /etc/sysconfig/logstash
- name: "Template Logstash keystore password"
  template:
    src: "logstash.j2"
    dest: "/etc/sysconfig/logstash"
    mode: '0600'
  notify: "Stop Logstash"
  become: true

# export LOGSTASH_KEYSTORE_PASS=xxxxx
- name: Add LOGSTASH_KEYSTORE_PASS in /etc/environment
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  loop: "{{ os_environment }}"
  become: true

# sudo -E /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash create
- name: "Create Logstash keystore"
  command: "/usr/share/logstash/bin/logstash-keystore --path.settings {{ logstash.conf_dir }} create"
  become: true
  become_flags: '-E'

# /usr/share/logstash/bin/logstash-keystore add LOGSTASH_WRITER_PASSWORD --path.settings /etc/logstash
- name: "Insert logstash writer password inside keystore"
  command: "echo '{{ logstash_internal.password }}' | /usr/share/logstash/bin/logstash-keystore add LOGSTASH_WRITER_PASSWORD --path.settings {{ logstash.conf_dir }}"
  become: true
