---
- name: "Template Logstash pipelines.yml"
  template:
    src: "pipelines.yml.j2"
    dest: "{{ logstash.conf_dir }}/pipelines.yml"
  become: true

- name: "Template Logstash filebeat pipeline"
  template:
    src: "filebeat-pipeline.conf.j2"
    dest: "{{ logstash.conf_dir }}/conf.d/filebeat-pipeline.conf"
  notify: "Restart Logstash"
  become: true
