---
- name: "Preflight Checks"
  include_tasks: "00-preflight-checks.yml"
  
- name: "Creates Logstash keystore"
  include_tasks: "01-logstash-keystore.yml"

- name: "Configure Logstash"
  include_tasks: "02-configure.yml"
